name: lost_found_app
description: A Lost and Found Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4 
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_native_splash: "^2.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  
flutter:
  uses-material-design: true